SELECT DNAME DEN_DEP, ENAME NUME, HIREDATE DATA_ANG, 
	SUBSTR(HIREDATE,4,2) LUNA_PRIMA, SAL SALARIU, COMM COMISION,ROUND(SAL*0.15,2) PRIMA
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND MONTHS_BETWEEN(SYSDATE, HIREDATE) >300 
AND NVL(COMM,0)=0;
 


SELECT DNAME DEN_DEP, ENAME NUME, HIREDATE DATA_ANG, 
	TO_CHAR(HIREDATE,'MON') LUNA_PRIMA, SAL SALARIU, COMM COMISION, ROUND(SAL*0.15,2) PRIMA
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND MONTHS_BETWEEN(SYSDATE, HIREDATE) >300 
AND NVL(COMM,0)=0;

SELECT DNAME DEN_DEP, ENAME NUME, HIREDATE DATA_ANG, 
	TO_CHAR(TO_DATE(RTRIM(HIREDATE,'-')),'MON') LUNA_PRIMA, SAL SALARIU, COMM COMISION, ROUND(SAL*0.15,2) PRIMA
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND MONTHS_BETWEEN(SYSDATE, HIREDATE) >300 
AND NVL(COMM,0)=0;

SELECT DNAME DEN_DEP, ENAME NUME, HIREDATE DATA_ANG, 
	TO_CHAR(HIREDATE,'MON') LUNA_PRIMA, SAL SALARIU, COMM COMISION, ROUND(SAL*0.15,2) PRIMA
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND ADD_MONTHS(HIREDATE,300) <SYSDATE 
AND NVL(COMM,0)=0;



 